### ISSUE TITLE
Feature request: Images

### ISSUE THREAD

**Issue by JakeHedman** [hanford/remark-slate#6]
Image support would be nice, are PRs welcome?

**Comment by hanford** [comment]
PR's are totally welcome!

**Comment by blorenz** [comment]
I took a stab at this but it hasn't been as straightforward as it seems. I was using the Slate Image example as my basis.  The Image example defines the images as Block Nodes which doesn't mix well with remark and valid Markdown.  Changing the Image example to be an inline Slate Element resulted in me having to modify the `remark-slate` serializer to do the similar inline checking that it does for a `link` to not put extra breaks around it because of the built-in constraints for Slate listed at https://docs.slatejs.org/concepts/10-normalizing [constraint number 4, in-particular about inline nodes]. This serialized as one would expect but the deserialization does not conform to to these Slate constraints (links exhibit the same behavior but get corrected upon additional content entry in the Slate editor). I've been throwing darts to attempt to make this work but have come up short thus far.
